[workspace]
members = [
  "crates/backend",
  "crates/common",
  "crates/iced-frontend",
  "crates/portal-filechooser",
  "crates/gtk-frontend",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[patch.crates-io]
iced_wgpu = { path = "vendor/iced-wgpu" }
iced_widget = { path = "vendor/iced-widget" }
