# Iron File default profile
name = "Default"
color_mode = "system"

[theme]
light_highlight = "#4f7cac"
dark_highlight = "#2b313b"

[browser]
item_size = 32
layout = "list"
preview_enabled = false
show_hidden_files = false
single_click_opens_folders = false
terminal_command = "default"
sidebar_width = 180
icon_theme = "bundled"
thumbnail_location = "~/.cache/iron-file/thumbnails"

[[sidebar_locations]]
label = "Home"
path = "~/"

[[sidebar_locations]]
label = "Downloads"
path = "~/Downloads"

[[sidebar_locations]]
label = "Pictures"
path = "~/Pictures"
