# Iron File default profile
name = "Default"
color_mode = "system"

[theme]
light_highlight = "#4f7cac"
dark_highlight = "#2b313b"
background_opacity = 100
context_menu_blur_strength = 2
context_menu_blur_kernel_size = "6sigma+1"
border_radius = 6

[browser]
item_size = 32
layout = "list"
preview_enabled = false
show_hidden_files = false
single_click_opens_folders = false
terminal_command = "default"
sidebar_width = 180
icon_theme = "bundled"
thumbnail_location = "~/.cache/iron-file/thumbnails"
file_context_menu_items = [
  "open",
  "copy-location",
  "copy-selection",
  "delete-selection",
]
folder_context_menu_items = [
  "create-folder",
  "create-file",
  "copy-location",
  "copy-selection",
  "delete-selection",
  "paste",
  "toggle-sidebar-location",
  "create-symlink",
  "add-symlink-to-paste-buffer",
  "open-terminal",
]
quick_toolbar_items = [
  "toggle-hidden-files",
  "compress-selection",
  "extract-selection",
]

[[sidebar_locations]]
label = "Home"
path = "~/"

[[sidebar_locations]]
label = "Downloads"
path = "~/Downloads"

[[sidebar_locations]]
label = "Pictures"
path = "~/Pictures"
