# Iron File default profile
name = "Default"
color_mode = "system"

[theme]
light_highlight = "#4f7cac"
dark_highlight = "#85b7eb"

[browser]
item_size = 32
layout = "list"
preview_enabled = false
single_click_opens_folders = false
terminal_command = "default"

[[sidebar_locations]]
label = "Home"
path = "~/"

[[sidebar_locations]]
label = "Downloads"
path = "~/Downloads"

[[sidebar_locations]]
label = "Pictures"
path = "~/Pictures"
