#!/usr/bin/env sh

set -eu

name=${1:?usage: save-file NAME [PATH]}
shift

case "$name" in
  '' | . | .. | */*)
    printf '%s\n' 'save-file: NAME must be a simple file name' >&2
    exit 2
    ;;
esac

exec cargo run --package iron-file-iced -- \
  --mode picker --folder --single --save-name "$name" "$@"
